require 'sinatra/base'
require_relative '../lib/player'
require_relative '../lib/game'
require_relative '../lib/board'
require_relative '../lib/cell'
require_relative '../lib/ship'
require_relative '../lib/water'

require_relative './controllers/application_controller'
require_relative './controllers/waiting_controller'
require_relative './controllers/play_controller'
require_relative './controllers/user_controller'
